EQUIPOS_ADMITIDOS = (
    ('ALEMANIA','Alemania - (Europa)'),	
    ('ARABIA SAUDITA','Arabia Saudita - (Asia)'),	
    ('ARGENTINA','Argentina - (Sudamérica)'),	
    ('AUSTRALIA','Australia - (Asia)'),	
    ('BÉLGICA','Bélgica - (Europa)'),	
    ('BRASIL','Brasil - (Sudamérica)'),	
    ('CAMERÚN','Camerún - (África)'),	
    ('CANADÁ','Canadá - (Concacaf)'),	
    ('COSTA RICA','Costa Rica - (Concacaf)'),
    ('COREA DEL SUR','Corea Del Sur - (Asia)'),	
    ('CROACIA','Croacia - (Europa)'),	
    ('DINAMARCA','Dinamarca - (Europa)'),	
    ('ECUADOR','Ecuador - (Sudamérica)'),	
    ('ESPAÑA','España - (Europa)'),	
    ('ESTADOS UNIDOS','Estados Unidos - (Concacaf)'),	
    ('FRANCIA','Francia - (Europa)'),	
    ('GALES','Gales - (Europa)'),	
    ('GHANA','Ghana - (África)'),	
    ('INGLATERRA','Inglaterra - (Europa)'),	
    ('IRÁN','Irán - (Asia)'),	
    ('JAPÓN','Japón - (Asia)'),	
    ('MARRUECOS','Marruecos - (África)'),	
    ('MÉXICO','México - (Concacaf)'),	
    ('PAISES BAJOS','Paises Bajos - (Europa)'),	
    ('POLONIA','Polonia - (Europa)'),	
    ('PORTUGAL','Portugal - (Europa)'),	
    ('QATAR','Qatar - (Asia)'),	
    ('SUIZA','Suiza - (Europa)'),	
    ('SENEGAL','Senegal - (África)'),	
    ('SERBIA','Serbia - (Europa)'),	
    ('TUNEZ','Tunez - (África)'),	
    ('URUGUAY','Uruguay - (Sudamérica)'),	
)

POSICIONES_DE_JUEGO = (
    ('POR','Portero'),
    ('CAD','Carrilero Derecho'),
    ('LTD','Lateral Derecho'),
    ('DFC','Defensa Central'),
    ('LTI','Lateral Izquierdo'),
    ('CAI','Carrilero Izquierdo'),
    ('MCD','Medio Centro Defensivo'),
    ('MD','Medio Derecho'),
    ('MC','Medio Centro'),
    ('MI','Medio Izquierdo'),
    ('MCO','Medio Centro Ofensivo'),
    ('SDD','Segundo Delantero Derecho'),
    ('MP','Media Punta'),
    ('SDI','Segundo Delantero Izquierdo'),
    ('ED','Extremo Derecho'),
    ('DC','Delantero Centro'),
    ('EI','Extremo Izquierdo'),
)

ROLES_ADMINISTRATIVOS = (
    ('TEC','Técnico'),
    ('AS','Asistente'),
    ('MED','Médico'),
    ('PRE','Preparador')
)

